// Code generated by scripts/generate-client.mjs from openapi/gateway.schema.json. DO NOT EDIT.

import type {
  ChatCompletionRequest,
  ChatCompletionResponse,
  ModelListResponse,
  CreateAPIKeyRequest,
  APIKeyView,
  APIKeyListResponse,
  CreateIngestionRequest,
  IngestionJobView,
  ModelCatalogResponse,
  ModelDetailView,
  CreateBenchmarkRunRequest,
  BenchmarkRunView,
  SessionCostView,
} from "./types";

export class APIError extends Error {
  status: number;
  code?: string;
  requestId?: string;
  constructor(status: number, message: string, code?: string, requestId?: string) {
    super(message);
    this.name = "APIError";
    this.status = status;
    this.code = code;
    this.requestId = requestId;
  }
}

export interface GatewayClientOptions {
  baseURL: string;
  apiKey?: string;
}

export class GatewayClient {
  private baseURL: string;
  private apiKey?: string;

  constructor(opts: GatewayClientOptions) {
    this.baseURL = opts.baseURL.replace(/\/$/, "");
    this.apiKey = opts.apiKey;
  }

  private headers(extra?: Record<string, string>): Record<string, string> {
    const headers: Record<string, string> = { "Content-Type": "application/json", ...extra };
    if (this.apiKey) headers["Authorization"] = `Bearer ${this.apiKey}`;
    return headers;
  }

  private async raise(res: Response): Promise<never> {
    let message = res.statusText;
    let code: string | undefined;
    let requestId: string | undefined;
    try {
      const body = await res.json();
      if (body?.error) {
        message = body.error.message ?? message;
        code = body.error.code;
        requestId = body.error.request_id;
      }
    } catch {
      // body was not JSON - fall back to statusText
    }
    throw new APIError(res.status, message, code, requestId);
  }

  async createChatCompletion(body: ChatCompletionRequest): Promise<ChatCompletionResponse> {
    const res = await fetch(`${this.baseURL}/v1/chat/completions`, {
      method: "POST",
      headers: this.headers(),
      body: JSON.stringify(body),
      credentials: "include",
    });
    if (!res.ok) return this.raise(res);
    return (await res.json()) as ChatCompletionResponse;
  }

  async listModels(): Promise<ModelListResponse> {
    const res = await fetch(`${this.baseURL}/v1/models`, {
      method: "GET",
      headers: this.headers(),
      body: undefined,
      credentials: "include",
    });
    if (!res.ok) return this.raise(res);
    return (await res.json()) as ModelListResponse;
  }

  async createAPIKey(body: CreateAPIKeyRequest): Promise<APIKeyView> {
    const res = await fetch(`${this.baseURL}/v1/api-keys`, {
      method: "POST",
      headers: this.headers(),
      body: JSON.stringify(body),
      credentials: "include",
    });
    if (!res.ok) return this.raise(res);
    return (await res.json()) as APIKeyView;
  }

  async listAPIKeys(): Promise<APIKeyListResponse> {
    const res = await fetch(`${this.baseURL}/v1/api-keys`, {
      method: "GET",
      headers: this.headers(),
      body: undefined,
      credentials: "include",
    });
    if (!res.ok) return this.raise(res);
    return (await res.json()) as APIKeyListResponse;
  }

  async revokeAPIKey(id: string): Promise<void> {
    const res = await fetch(`${this.baseURL}/v1/api-keys/${encodeURIComponent(id)}`, {
      method: "DELETE",
      headers: this.headers(),
      body: undefined,
      credentials: "include",
    });
    if (!res.ok) return this.raise(res);
  }

  async createIngestion(body: CreateIngestionRequest): Promise<IngestionJobView> {
    const res = await fetch(`${this.baseURL}/v1/ingestions`, {
      method: "POST",
      headers: this.headers(),
      body: JSON.stringify(body),
      credentials: "include",
    });
    if (!res.ok) return this.raise(res);
    return (await res.json()) as IngestionJobView;
  }

  async getIngestion(id: string): Promise<IngestionJobView> {
    const res = await fetch(`${this.baseURL}/v1/ingestions/${encodeURIComponent(id)}`, {
      method: "GET",
      headers: this.headers(),
      body: undefined,
      credentials: "include",
    });
    if (!res.ok) return this.raise(res);
    return (await res.json()) as IngestionJobView;
  }

  async listDashboardModels(): Promise<ModelCatalogResponse> {
    const res = await fetch(`${this.baseURL}/v1/dashboard/models`, {
      method: "GET",
      headers: this.headers(),
      body: undefined,
      credentials: "include",
    });
    if (!res.ok) return this.raise(res);
    return (await res.json()) as ModelCatalogResponse;
  }

  async getDashboardModel(id: string): Promise<ModelDetailView> {
    const res = await fetch(`${this.baseURL}/v1/dashboard/models/${encodeURIComponent(id)}`, {
      method: "GET",
      headers: this.headers(),
      body: undefined,
      credentials: "include",
    });
    if (!res.ok) return this.raise(res);
    return (await res.json()) as ModelDetailView;
  }

  async createBenchmarkRun(body: CreateBenchmarkRunRequest): Promise<BenchmarkRunView> {
    const res = await fetch(`${this.baseURL}/v1/dashboard/benchmarks`, {
      method: "POST",
      headers: this.headers(),
      body: JSON.stringify(body),
      credentials: "include",
    });
    if (!res.ok) return this.raise(res);
    return (await res.json()) as BenchmarkRunView;
  }

  async getSessionCost(id: string): Promise<SessionCostView> {
    const res = await fetch(`${this.baseURL}/v1/dashboard/deployments/${encodeURIComponent(id)}/session`, {
      method: "GET",
      headers: this.headers(),
      body: undefined,
      credentials: "include",
    });
    if (!res.ok) return this.raise(res);
    return (await res.json()) as SessionCostView;
  }

}
