// Code generated by scripts/generate-client.mjs from openapi/gateway.schema.json. DO NOT EDIT.

export interface ChatMessage {
  role: string;
  content: string;
}

export interface ChatCompletionRequest {
  model: string;
  messages: ChatMessage[];
  temperature?: number;
  top_p?: number;
  max_tokens?: number;
  stream?: boolean;
}

export interface ChatCompletionUsage {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
}

export interface ChatCompletionChoice {
  index: number;
  message: ChatMessage;
  finish_reason: string;
}

export interface ChatCompletionResponse {
  id: string;
  object: string;
  created: number;
  model: string;
  choices: ChatCompletionChoice[];
  usage: ChatCompletionUsage;
}

export interface ChatCompletionChunkDelta {
  role?: string;
  content?: string;
}

export interface ChatCompletionChunkChoice {
  index: number;
  delta: ChatCompletionChunkDelta;
  finish_reason: string | null;
}

export interface ChatCompletionChunk {
  id: string;
  object: string;
  created: number;
  model: string;
  choices: ChatCompletionChunkChoice[];
  usage?: ChatCompletionUsage;
}

export interface ModelObject {
  id: string;
  object: string;
  created: number;
  owned_by: string;
}

export interface ModelListResponse {
  object: string;
  data: ModelObject[];
}

export interface APIError {
  error: APIErrorDetail;
}

export interface APIErrorDetail {
  code: string;
  message: string;
  request_id?: string;
}

export interface APIKeyView {
  id: string;
  display_prefix: string;
  scopes: string[];
  last_used_at?: string;
  revoked_at?: string;
  created_at: string;
  key?: string;
}

export interface APIKeyListResponse {
  data: APIKeyView[];
}

export interface CreateAPIKeyRequest {
  scopes: string[];
}

export interface IngestionJobView {
  id: string;
  repo_url: string;
  revision: string;
  state: string;
  bytes_total: number;
  bytes_downloaded: number;
  error_message?: string;
  model_id?: string;
}

export interface CreateIngestionRequest {
  repo_url: string;
  revision?: string;
}
