#!/usr/bin/env node
// Reads openapi/gateway.schema.json and emits src/lib/api/types.ts and
// src/lib/api/client.ts. Run via `npm run generate:client`. Do not
// hand-edit the two generated files - edit the schema and regenerate.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, "..");
const schema = JSON.parse(
  readFileSync(path.join(root, "openapi", "gateway.schema.json"), "utf8"),
);

const GENERATED_HEADER = `// Code generated by scripts/generate-client.mjs from openapi/gateway.schema.json. DO NOT EDIT.\n`;

function fieldToTS(fieldName, fieldType) {
  const optional = fieldName.endsWith("?");
  const name = optional ? fieldName.slice(0, -1) : fieldName;
  return `  ${name}${optional ? "?" : ""}: ${fieldType};`;
}

function renderTypes() {
  const lines = [GENERATED_HEADER];
  for (const [typeName, fields] of Object.entries(schema.types)) {
    lines.push(`export interface ${typeName} {`);
    for (const [fieldName, fieldType] of Object.entries(fields)) {
      lines.push(fieldToTS(fieldName, fieldType));
    }
    lines.push("}", "");
  }
  return lines.join("\n");
}

function renderClient() {
  const lines = [
    GENERATED_HEADER,
    `import type {`,
    ...[...new Set(schema.endpoints.flatMap((e) => [e.request, e.response].filter(Boolean)))].map(
      (t) => `  ${t},`,
    ),
    `} from "./types";`,
    "",
    `export class APIError extends Error {`,
    `  status: number;`,
    `  code?: string;`,
    `  requestId?: string;`,
    `  constructor(status: number, message: string, code?: string, requestId?: string) {`,
    `    super(message);`,
    `    this.name = "APIError";`,
    `    this.status = status;`,
    `    this.code = code;`,
    `    this.requestId = requestId;`,
    `  }`,
    `}`,
    "",
    `export interface GatewayClientOptions {`,
    `  baseURL: string;`,
    `  apiKey?: string;`,
    `}`,
    "",
    `export class GatewayClient {`,
    `  private baseURL: string;`,
    `  private apiKey?: string;`,
    "",
    `  constructor(opts: GatewayClientOptions) {`,
    `    this.baseURL = opts.baseURL.replace(/\\/$/, "");`,
    `    this.apiKey = opts.apiKey;`,
    `  }`,
    "",
    `  private headers(extra?: Record<string, string>): Record<string, string> {`,
    `    const headers: Record<string, string> = { "Content-Type": "application/json", ...extra };`,
    `    if (this.apiKey) headers["Authorization"] = \`Bearer \${this.apiKey}\`;`,
    `    return headers;`,
    `  }`,
    "",
    `  private async raise(res: Response): Promise<never> {`,
    `    let message = res.statusText;`,
    `    let code: string | undefined;`,
    `    let requestId: string | undefined;`,
    `    try {`,
    `      const body = await res.json();`,
    `      if (body?.error) {`,
    `        message = body.error.message ?? message;`,
    `        code = body.error.code;`,
    `        requestId = body.error.request_id;`,
    `      }`,
    `    } catch {`,
    `      // body was not JSON - fall back to statusText`,
    `    }`,
    `    throw new APIError(res.status, message, code, requestId);`,
    `  }`,
    "",
  ];

  for (const endpoint of schema.endpoints) {
    const argType = endpoint.request ? `body: ${endpoint.request}` : "";
    const returnType = endpoint.response ?? "void";
    lines.push(
      `  async ${endpoint.name}(${argType}): Promise<${returnType}> {`,
      `    const res = await fetch(\`\${this.baseURL}${endpoint.path}\`, {`,
      `      method: "${endpoint.method}",`,
      `      headers: this.headers(),`,
      endpoint.request ? `      body: JSON.stringify(body),` : `      body: undefined,`,
      `      credentials: "include",`,
      `    });`,
      `    if (!res.ok) return this.raise(res);`,
      returnType === "void" ? `  }` : `    return (await res.json()) as ${returnType};\n  }`,
      "",
    );
  }

  lines.push(`}`, "");
  return lines.join("\n");
}

const outDir = path.join(root, "src", "lib", "api");
mkdirSync(outDir, { recursive: true });
writeFileSync(path.join(outDir, "types.ts"), renderTypes());
writeFileSync(path.join(outDir, "client.ts"), renderClient());
console.log("generated src/lib/api/types.ts and src/lib/api/client.ts");
